const arrLeiders = [
	{
		id: 1,
		naam: "Darko Boesmans",
		url_afbeelding: "darko.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 2,
		naam: "Lana Van Nieuwenhuysen",
		url_afbeelding: "lana.jpg",
		afdeling: "Aspi",
		nummer: "+324 78 51 20 35",
	},
	{
		id: 3,
		naam: "Annelore Buyl",
		url_afbeelding: "annelore.jpg",
		afdeling: "Tito",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 4,
		naam: "Anouck Duerinck",
		url_afbeelding: "anouck.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 5,
		naam: "Yanis Boyata",
		url_afbeelding: "yanis.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 6,
		naam: "Britt De Naer",
		url_afbeelding: "britt.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 7,
		naam: "Eron Callaert",
		url_afbeelding: "eron.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 8,
		naam: "Ilana Wellekens",
		url_afbeelding: "ilana.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 9,
		naam: "Jana Verhaegen",
		url_afbeelding: "jana.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 10,
		naam: "Litsa Boesmans",
		url_afbeelding: "litsa.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 11,
		naam: "Louise De Backer",
		url_afbeelding: "louise.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 12,
		naam: "Margot Temmerman",
		url_afbeelding: "margot.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 13,
		naam: "Robbe Van Riet",
		url_afbeelding: "robbe.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 14,
		naam: "Robin De Croock",
		url_afbeelding: "robin.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 15,
		naam: "Sofie van Riet",
		url_afbeelding: "sofie.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 16,
		naam: "Winke Kindermans",
		url_afbeelding: "winke.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 17,
		naam: "Kevin Thiry",
		url_afbeelding: "kevin.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
];
