const arrLeiders = [
	{
		id: 1,
		naam: "Darko Boesmans",
		url_afbeelding: "darko.jpg",
		afdeling: "Pinkels",
		nummer: "+324 84 38 11 60",
	},
	{
		id: 2,
		naam: "Lana Van Nieuwenhuysen",
		url_afbeelding: "lana.jpg",
		afdeling: "Aspi",
		nummer: "+324 78 51 20 35",
	},
	{
		id: 3,
		naam: "Annelore Buyl",
		url_afbeelding: "annelore.jpg",
		afdeling: "Tito",
		nummer: "+324 72 93 20 83",
	},
	{
		id: 4,
		naam: "Anouck Duerinck",
		url_afbeelding: "anouck.jpg",
		afdeling: "Rakwi",
		nummer: "+324 77 09 36 95",
	},
	{
		id: 5,
		naam: "Yanis Boyata",
		url_afbeelding: "yanis.jpg",
		afdeling: "Pinkels",
		nummer: "+324 67 67 35 72",
	},
	{
		id: 6,
		naam: "Britt De Naer",
		url_afbeelding: "britt.jpg",
		afdeling: "Pinkels",
		nummer: "+324 77 32 28 73",
	},
	{
		id: 7,
		naam: "Eron Callaert",
		url_afbeelding: "eron.jpg",
		afdeling: "Rakwi",
		nummer: "+324 78 10 37 61 ",
	},
	{
		id: 8,
		naam: "Ilana Wellekens",
		url_afbeelding: "ilana.jpg",
		afdeling: "Rakwi",
		nummer: "+324 70 92 43 59",
	},
	{
		id: 9,
		naam: "Jana Verhaegen",
		url_afbeelding: "jana.jpg",
		afdeling: "Aspi",
		nummer: "+324 74 41 03 72",
	},
	{
		id: 10,
		naam: "Litsa Boesmans",
		url_afbeelding: "litsa.jpg",
		afdeling: "Speelclub",
		nummer: "+324 89 55 52 02",
	},
	{
		id: 11,
		naam: "Louise De Backer",
		url_afbeelding: "louise.jpg",
		afdeling: "Speelclub",
		nummer: "+324 71 68 22 13",
	},
	{
		id: 12,
		naam: "Margot Temmerman",
		url_afbeelding: "margot.jpg",
		afdeling: "Ket",
		nummer: "+324 73 93 70 71",
	},
	{
		id: 13,
		naam: "Robbe Van Riet",
		url_afbeelding: "robbe.jpg",
		afdeling: "Speelclub",
		nummer: "+324 77 33 87 45",
	},
	{
		id: 14,
		naam: "Robin De Croock",
		url_afbeelding: "robin.jpg",
		afdeling: "Tito",
		nummer: "+324 68 13 42 77",
	},
	{
		id: 15,
		naam: "Sofie van Riet",
		url_afbeelding: "sofie.jpg",
		afdeling: "Veebee",
		nummer: "+32 471 38 37 01",
	},
	{
		id: 16,
		naam: "Winke Kindermans",
		url_afbeelding: "winke.jpg",
		afdeling: "Keti",
		nummer: "+324 74 63 13 85",
	},
	{
		id: 17,
		naam: "Kevin Thiry",
		url_afbeelding: "kevin.jpg",
		afdeling: "Veebee",
		nummer: "+32 478 28 96 80",
	},
];
